name: ci
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: build node
      working-directory: ./node
      run: go build -v ./...
    - name: test node
      working-directory: ./node
      run: go test -v ./...

    - name: build nodesmetadata
      working-directory: ./nodesmetadata
      run: go build -v ./...
    - name: test nodesmetadata
      working-directory: ./nodesmetadata
      run: go test -v ./...

    - name: build proxy
      working-directory: ./proxy
      run: go build -v ./...
    - name: test proxy
      working-directory: ./proxy
      run: go test -v ./...
